# Generated by Django 5.1 on 2024-08-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='correo',
            field=models.CharField(default='illescasluis958@gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
