# Generated by Django 5.1 on 2024-08-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='direccion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
