# Generated by Django 5.1 on 2024-08-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='correo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
